version: "3.7"

services:
  chattie:
    container_name: chattie
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - my_network
    links:
      - redis

  redis:
    image: "redis:7"
    container_name: "redis"
    ports:
      - "6379:6379"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge